[video]
cameras = [
    #{ id="tp", location = "rtsp://tapo00:password@192.168.8.100:554/stream1",model = "yolov3", labels = [ 14 ] },
    { id="00", location = "rtsp://RTSP_SERVER_IP:8554/test00", model = "yolov3", labels = [ 14 ] },
    { id="00", location = "rtsp://RTSP_SERVER_IP:8554/test00", model = "yolov3", labels = [ 14 ] },
    { id="01", location = "rtsp://RTSP_SERVER_IP:8554/test01", model = "yolov3", labels = [ 1, 5, 6, 13 ] },
    { id="02", location = "rtsp://RTSP_SERVER_IP:8554/test02", model = "yolov3", labels = [ 1, 5, 6, 13 ] },
    { id="03", location = "rtsp://RTSP_SERVER_IP:8554/test03", model = "yolov3", labels = [ 1, 5, 6, 13 ] },
    { id="04", location = "rtsp://RTSP_SERVER_IP:8554/test04", model = "yolov3", labels = [ 1, 5, 6, 13 ] },
    { id="05", location = "rtsp://RTSP_SERVER_IP:8554/test05", model = "yolov3", labels = [ 1, 5, 6, 13 ] },
    { id="06", location = "rtsp://RTSP_SERVER_IP:8554/test06", model = "yolov3", labels = [ 1, 5, 6, 13 ] },
    { id="07", location = "rtsp://RTSP_SERVER_IP:8554/test07", model = "yolov3", labels = [ 1, 5, 6, 13 ] },
    { id="08", location = "rtsp://RTSP_SERVER_IP:8554/test08", model = "yolov3", labels = [ 1, 5, 6, 13 ] },
    { id="09", location = "rtsp://RTSP_SERVER_IP:8554/test09", model = "yolov3", labels = [ 1, 5, 6, 13 ] },
    { id="0a", location = "rtsp://RTSP_SERVER_IP:8554/test0a", model = "yolov3", labels = [ 1, 5, 6, 13 ] },
    { id="0b", location = "rtsp://RTSP_SERVER_IP:8554/test0b", model = "yolov3", labels = [ 1, 5, 6, 13 ] },
    { id="0c", location = "rtsp://RTSP_SERVER_IP:8554/test0c", model = "yolov3", labels = [ 1, 5, 6, 13 ] },
    { id="0d", location = "rtsp://RTSP_SERVER_IP:8554/test0d", model = "yolov3", labels = [ 1, 5, 6, 13 ] },
    { id="0e", location = "rtsp://RTSP_SERVER_IP:8554/test0e", model = "yolov3", labels = [ 1, 5, 6, 13 ] },
]

device-index = -1

focus-size = 3
focus-duration = 3

output-rtsp = 1

output-width = 1920
output-height = 1080
output-bitrate = 16000

#output-width = 3840
#output-height = 2160
#output-bitrate = 16000

rtsp-server-location = "rtsp://RTSP_SERVER_IP:8554/test"

[ml.yolov3]
xmodels = [ "/usr/share/vitis_ai_library/models/yolov3_voc_tf/yolov3_voc_tf.xmodel" ]
port = 5555
max_batch_latency = 100
max_batch_size = 13
num_workers = 2

[ml.carclassification]
xmodels = [
    "/usr/share/vitis_ai_library/models/chen_color_resnet18_pt/chen_color_resnet18_pt.xmodel",
    "/usr/share/vitis_ai_library/models/vehicle_make_resnet18_pt/vehicle_make_resnet18_pt.xmodel",
    "/usr/share/vitis_ai_library/models/vehicle_type_resnet18_pt/vehicle_type_resnet18_pt.xmodel",
]
port = 5556
max_batch_latency = 100
max_batch_size = 13
num_workers = 3

[ml.bcc]
xmodels = [ "/workspace/demo/docker/models/bcc/deploy.xmodel" ]
port = 5557
max_batch_latency = 100
max_batch_size = 13
num_workers = 2

