{
 "title": "Crowd Monitor Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Monitor",
   "type": "text",
   "gridPos": { "h": 25, "w": 17, "x": 0, "y": 0 },
   "options": {
    "content": "<iframe src=\"https://%HOST_SERVER_IP%:8888/test\"\n scrolling=\"no\" width=\"100%\" height=\"100%\"\n frameborder=\"0\" style=\"border:0;\" allowfullscreen=\"\"></iframe>"
   }
  },
  {
   "title": "All",
   "type": "timeseries",
   "gridPos": { "h": 25, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"bucket\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"count\")\r\n    |> window(every: 5s)\r\n    |> mean()\r\n    |> duplicate(column: \"_stop\", as: \"_time\")\r\n    |> window(every: inf)"
    }
   ]
  },
  {
   "title": "Camera 00",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "from(bucket:\"bucket\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"count\" and r.camera == \"00\")\r\n    |> window(every: 5s)\r\n    |> mean()\r\n    |> duplicate(column: \"_stop\", as: \"_time\")\r\n    |> window(every: inf)"
    }
   ]
  },
  {
   "title": "Camera 01",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "query": "from(bucket:\"bucket\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"count\" and r.camera == \"01\")\r\n    |> window(every: 5s)\r\n    |> mean()\r\n    |> duplicate(column: \"_stop\", as: \"_time\")\r\n    |> window(every: inf)"
    }
   ]
  },
  {
   "title": "Camera 02",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "targets": [
    {
     "query": "from(bucket:\"bucket\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"count\" and r.camera == \"02\")\r\n    |> window(every: 5s)\r\n    |> mean()\r\n    |> duplicate(column: \"_stop\", as: \"_time\")\r\n    |> window(every: inf)"
    }
   ]
  },
  {
   "title": "Camera 03",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "query": "from(bucket:\"bucket\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"count\" and r.camera == \"03\")\r\n    |> window(every: 5s)\r\n    |> mean()\r\n    |> duplicate(column: \"_stop\", as: \"_time\")\r\n    |> window(every: inf)"
    }
   ]
  }
 ]
}